const POSTGRES_SCHEMA_VERSION = 1;

const POSTGRES_TABLES = [
  'configurations',
  'warnings',
  'dashboard_sessions',
  'dashboard_oauth_states',
  'audit_logs',
  'change_history',
  'suggestions',
  'guild_installations',
  'creator_metrics',
  'command_usage',
  'guild_activation_progress',
  'premium_entitlements',
  'premium_founder_trials',
  'premium_user_guilds',
  'community_giveaways',
  'community_giveaway_entries',
  'support_requests',
  'support_messages',
  'support_events',
  'support_staff',
  'twitch_connections',
  'twitch_oauth_states',
  'twitch_custom_commands',
  'twitch_chat_config',
  'twitch_runtime_status',
  'twitch_processed_messages',
  'twitch_eventsub_messages',
];

const POSTGRES_SCHEMA_SQL = `
CREATE TABLE IF NOT EXISTS fyxbot_schema_migrations (
  version INTEGER PRIMARY KEY,
  applied_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS configurations (
  guild_id TEXT NOT NULL,
  section TEXT NOT NULL,
  value TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  PRIMARY KEY (guild_id, section)
);

CREATE TABLE IF NOT EXISTS warnings (
  id TEXT PRIMARY KEY,
  guild_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  moderator_id TEXT NOT NULL,
  reason TEXT NOT NULL,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS warnings_lookup ON warnings(guild_id, user_id, created_at);

CREATE TABLE IF NOT EXISTS dashboard_sessions (
  token_hash TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  expires_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS dashboard_oauth_states (
  state_hash TEXT PRIMARY KEY,
  expires_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  color INTEGER NOT NULL,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS audit_logs_guild ON audit_logs(guild_id, id DESC);

CREATE TABLE IF NOT EXISTS change_history (
  id TEXT PRIMARY KEY,
  guild_id TEXT NOT NULL,
  actor_id TEXT NOT NULL,
  actor_name TEXT NOT NULL,
  kind TEXT NOT NULL,
  title TEXT NOT NULL,
  summary TEXT NOT NULL,
  details TEXT NOT NULL DEFAULT '{}',
  backup_file TEXT,
  reversible INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'applied',
  created_at TEXT NOT NULL,
  rolled_back_at TEXT,
  rolled_back_by TEXT
);
CREATE INDEX IF NOT EXISTS change_history_guild ON change_history(guild_id, created_at DESC);

CREATE TABLE IF NOT EXISTS suggestions (
  id TEXT PRIMARY KEY,
  guild_id TEXT NOT NULL,
  channel_id TEXT NOT NULL,
  message_id TEXT NOT NULL,
  author_id TEXT NOT NULL,
  author_name TEXT NOT NULL,
  anonymous INTEGER NOT NULL DEFAULT 0,
  idea TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  reviewed_by TEXT,
  reviewed_at TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS suggestions_guild ON suggestions(guild_id, created_at DESC);

CREATE TABLE IF NOT EXISTS guild_installations (
  guild_id TEXT PRIMARY KEY,
  guild_name TEXT NOT NULL,
  member_count INTEGER NOT NULL DEFAULT 0,
  first_seen_at TEXT NOT NULL,
  last_seen_at TEXT NOT NULL,
  removed_at TEXT
);

CREATE TABLE IF NOT EXISTS creator_metrics (
  day TEXT PRIMARY KEY,
  guild_count INTEGER NOT NULL,
  member_count INTEGER NOT NULL,
  recorded_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS command_usage (
  day TEXT NOT NULL,
  guild_id TEXT NOT NULL,
  command_name TEXT NOT NULL,
  success_count INTEGER NOT NULL DEFAULT 0,
  failure_count INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (day, guild_id, command_name)
);
CREATE INDEX IF NOT EXISTS command_usage_day ON command_usage(day);

CREATE TABLE IF NOT EXISTS guild_activation_progress (
  guild_id TEXT PRIMARY KEY,
  tracking_started_at TEXT NOT NULL,
  last_observed_at TEXT,
  completed_steps INTEGER NOT NULL DEFAULT 0,
  step_keys TEXT NOT NULL DEFAULT '[]',
  activated_at TEXT,
  baseline INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS guild_activation_observed ON guild_activation_progress(last_observed_at);

CREATE TABLE IF NOT EXISTS premium_entitlements (
  entitlement_id TEXT PRIMARY KEY,
  sku_id TEXT NOT NULL,
  user_id TEXT,
  guild_id TEXT,
  starts_at TEXT,
  ends_at TEXT,
  deleted INTEGER NOT NULL DEFAULT 0,
  test INTEGER NOT NULL DEFAULT 0,
  observed_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS premium_entitlements_guild ON premium_entitlements(guild_id, sku_id, deleted, ends_at);
CREATE INDEX IF NOT EXISTS premium_entitlements_user ON premium_entitlements(user_id, sku_id, deleted, ends_at);

CREATE TABLE IF NOT EXISTS premium_founder_trials (
  user_id TEXT PRIMARY KEY,
  starts_at TEXT NOT NULL,
  ends_at TEXT NOT NULL,
  claimed_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS premium_founder_trials_ends ON premium_founder_trials(ends_at);

CREATE TABLE IF NOT EXISTS premium_user_guilds (
  user_id TEXT NOT NULL,
  guild_id TEXT NOT NULL,
  linked_at TEXT NOT NULL,
  PRIMARY KEY (user_id, guild_id)
);
CREATE INDEX IF NOT EXISTS premium_user_guilds_guild ON premium_user_guilds(guild_id, user_id);

CREATE TABLE IF NOT EXISTS community_giveaways (
  giveaway_id TEXT PRIMARY KEY,
  guild_id TEXT NOT NULL,
  channel_id TEXT NOT NULL,
  message_id TEXT NOT NULL,
  prize TEXT NOT NULL,
  winner_count INTEGER NOT NULL,
  ends_at TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TEXT NOT NULL,
  ended_at TEXT
);
CREATE INDEX IF NOT EXISTS community_giveaways_due ON community_giveaways(status, ends_at);
CREATE INDEX IF NOT EXISTS community_giveaways_guild ON community_giveaways(guild_id, status, ends_at);

CREATE TABLE IF NOT EXISTS community_giveaway_entries (
  giveaway_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  joined_at TEXT NOT NULL,
  PRIMARY KEY (giveaway_id, user_id),
  FOREIGN KEY (giveaway_id) REFERENCES community_giveaways(giveaway_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS community_giveaway_entries_lookup ON community_giveaway_entries(giveaway_id, joined_at);

CREATE TABLE IF NOT EXISTS support_requests (
  id TEXT PRIMARY KEY,
  guild_id TEXT NOT NULL,
  guild_name TEXT NOT NULL,
  requester_id TEXT NOT NULL,
  requester_name TEXT NOT NULL,
  category TEXT NOT NULL,
  subject TEXT NOT NULL,
  priority TEXT NOT NULL DEFAULT 'normal',
  status TEXT NOT NULL DEFAULT 'open',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  last_message_at TEXT NOT NULL,
  closed_at TEXT
);
CREATE INDEX IF NOT EXISTS support_requests_requester ON support_requests(requester_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS support_requests_guild ON support_requests(guild_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS support_requests_status ON support_requests(status, priority, updated_at DESC);

CREATE TABLE IF NOT EXISTS support_messages (
  id TEXT PRIMARY KEY,
  request_id TEXT NOT NULL,
  author_id TEXT NOT NULL,
  author_name TEXT NOT NULL,
  author_role TEXT NOT NULL,
  body TEXT NOT NULL,
  created_at TEXT NOT NULL,
  FOREIGN KEY (request_id) REFERENCES support_requests(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS support_messages_request ON support_messages(request_id, created_at);

CREATE TABLE IF NOT EXISTS support_events (
  id TEXT PRIMARY KEY,
  request_id TEXT NOT NULL,
  actor_id TEXT NOT NULL,
  actor_name TEXT NOT NULL,
  event_type TEXT NOT NULL,
  detail TEXT NOT NULL,
  created_at TEXT NOT NULL,
  FOREIGN KEY (request_id) REFERENCES support_requests(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS support_events_request ON support_events(request_id, created_at);

CREATE TABLE IF NOT EXISTS support_staff (
  user_id TEXT PRIMARY KEY,
  display_name TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('moderator', 'administrator')),
  granted_by TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS support_staff_role ON support_staff(role, updated_at DESC);

CREATE TABLE IF NOT EXISTS twitch_connections (
  guild_id TEXT PRIMARY KEY,
  broadcaster_user_id TEXT NOT NULL,
  broadcaster_login TEXT NOT NULL,
  broadcaster_display_name TEXT NOT NULL,
  access_token_encrypted TEXT NOT NULL,
  refresh_token_encrypted TEXT,
  scopes TEXT NOT NULL DEFAULT '[]',
  expires_at TEXT NOT NULL,
  enabled INTEGER NOT NULL DEFAULT 0 CHECK (enabled IN (0, 1)),
  connected_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS twitch_active_broadcaster
  ON twitch_connections(broadcaster_user_id) WHERE enabled = 1;
CREATE INDEX IF NOT EXISTS twitch_connections_enabled
  ON twitch_connections(enabled, updated_at);

CREATE TABLE IF NOT EXISTS twitch_oauth_states (
  state_hash TEXT PRIMARY KEY,
  guild_id TEXT NOT NULL,
  discord_user_id TEXT NOT NULL,
  expires_at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS twitch_oauth_states_guild ON twitch_oauth_states(guild_id, expires_at);

CREATE TABLE IF NOT EXISTS twitch_custom_commands (
  guild_id TEXT NOT NULL,
  name TEXT NOT NULL,
  response TEXT NOT NULL,
  enabled INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0, 1)),
  cooldown_seconds INTEGER NOT NULL DEFAULT 5 CHECK (cooldown_seconds BETWEEN 0 AND 3600),
  access_level TEXT NOT NULL DEFAULT 'everyone'
    CHECK (access_level IN ('everyone', 'subscriber', 'moderator', 'broadcaster')),
  usage_count INTEGER NOT NULL DEFAULT 0 CHECK (usage_count >= 0),
  updated_at TEXT NOT NULL,
  PRIMARY KEY (guild_id, name)
);

CREATE TABLE IF NOT EXISTS twitch_chat_config (
  guild_id TEXT PRIMARY KEY,
  enabled INTEGER NOT NULL DEFAULT 0 CHECK (enabled IN (0, 1)),
  prefix TEXT NOT NULL DEFAULT '!',
  link_protection INTEGER NOT NULL DEFAULT 1 CHECK (link_protection IN (0, 1)),
  caps_protection INTEGER NOT NULL DEFAULT 1 CHECK (caps_protection IN (0, 1)),
  repetition_protection INTEGER NOT NULL DEFAULT 1 CHECK (repetition_protection IN (0, 1)),
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS twitch_runtime_status (
  guild_id TEXT PRIMARY KEY,
  status TEXT NOT NULL,
  detail TEXT,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS twitch_processed_messages (
  guild_id TEXT NOT NULL,
  message_id TEXT NOT NULL,
  expires_at BIGINT NOT NULL,
  PRIMARY KEY (guild_id, message_id)
);
CREATE INDEX IF NOT EXISTS twitch_processed_messages_expiry
  ON twitch_processed_messages(guild_id, expires_at);

CREATE TABLE IF NOT EXISTS twitch_eventsub_messages (
  guild_id TEXT NOT NULL,
  message_id TEXT NOT NULL,
  received_at BIGINT NOT NULL,
  expires_at BIGINT NOT NULL,
  PRIMARY KEY (guild_id, message_id)
);
CREATE INDEX IF NOT EXISTS twitch_eventsub_messages_expiry
  ON twitch_eventsub_messages(guild_id, expires_at);
`;

module.exports = {
  POSTGRES_SCHEMA_SQL,
  POSTGRES_SCHEMA_VERSION,
  POSTGRES_TABLES,
};
